openapi: 3.0.3

paths:
  /health:
    get:
      summary: Verificar disponibilidade
      responses:
        "200":
          description: Serviço disponível

  /customers:
    get:
      tags:
        - Customers
      summary: Listar clientes
      responses:
        "200":
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string